Understand Fund Master

In [6]:
import os

print(os.listdir("../Data/raw"))

['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'Axis_Bluechip_NAV.csv', 'ICICI_Bluechip_NAV.csv', 'Kotak_Bluechip_NAV.csv', 'Nippon_LargeCap_NAV.csv', 'SBI_Bluechip_NAV.csv']

In [7]:
fund_master = pd.read_csv("../Data/raw/01_fund_master.csv")

In [8]:
import os
print(os.getcwd())

c:\Users\NEHA\OneDrive\Desktop\Mutual Fund Capstone Project\notebooks

In [9]:
import pandas as pd

fund_master = pd.read_csv("../Data/raw/01_fund_master.csv")

In [11]:
import os

print(os.listdir("../Data/raw"))

['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'Axis_Bluechip_NAV.csv', 'ICICI_Bluechip_NAV.csv', 'Kotak_Bluechip_NAV.csv', 'Nippon_LargeCap_NAV.csv', 'SBI_Bluechip_NAV.csv']

In [12]:
print(fund_master.columns.tolist())

['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

In [13]:
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [14]:
fund_master.describe(include="all")

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
count,40.000000,40,40,40,40,40,40,40,40.000000,40.000000,40.0,40.000000,40,40,40
unique,NaN,10,40,2,12,2,34,10,NaN,NaN,NaN,NaN,29,5,9
top,NaN,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2013-01-01,NIFTY 100 TRI,NaN,NaN,NaN,NaN,Sohini Andani,Moderate,EC01
freq,NaN,5,1,34,14,32,7,14,NaN,NaN,NaN,NaN,2,16,14
mean,120247.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.237000,0.812500,500.0,1277.500000,NaN,NaN,NaN
std,14534.998667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.386584,0.387091,0.0,1082.847031,NaN,NaN,NaN
min,100016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.550000,0.000000,500.0,100.000000,NaN,NaN,NaN
25%,118632.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.787500,1.000000,500.0,1000.000000,NaN,NaN,NaN
50%,119551.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.425000,1.000000,500.0,1000.000000,NaN,NaN,NaN
75%,120842.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.540000,1.000000,500.0,1000.000000,NaN,NaN,NaN
max,149324.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.640000,1.000000,500.0,5000.000000,NaN,NaN,NaN

In [15]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [20]:
print("Fund Houses:")
print(fund_master["fund_house"].unique())

print("\nCategories:")
print(fund_master["category"].unique())

print("\nSub Categories:")
print(fund_master["sub_category"].unique())

print("\nRisk Categories:")
print(fund_master["risk_category"].unique())

Fund Houses:
<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

Categories:
<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

Sub Categories:
<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

Risk Categories:
<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [21]:
print("Number of Fund Houses:", fund_master["fund_house"].nunique())
print("Number of Categories:", fund_master["category"].nunique())
print("Number of Sub Categories:", fund_master["sub_category"].nunique())
print("Number of Risk Categories:", fund_master["risk_category"].nunique())

Number of Fund Houses: 10
Number of Categories: 2
Number of Sub Categories: 12
Number of Risk Categories: 5

In [22]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [24]:
nav_history = pd.read_csv("../Data/raw/02_nav_history.csv")

In [25]:
print(nav_history.columns.tolist())

['amfi_code', 'date', 'nav']

In [28]:
import pandas as pd

# Load datasets
fund_master = pd.read_csv("../Data/raw/01_fund_master.csv")
nav_history = pd.read_csv("../Data/raw/02_nav_history.csv")

# Find AMFI codes that are in fund_master but missing in nav_history
missing_codes = fund_master[
    ~fund_master["amfi_code"].isin(nav_history["amfi_code"])
]

print("Number of missing AMFI codes:", len(missing_codes))
display(missing_codes.head())

# Save the report
missing_codes.to_csv("../reports/data_quality_report.csv", index=False)

print("✅ Data quality report saved to reports/data_quality_report.csv")

Number of missing AMFI codes: 0

Empty DataFrame
Columns: [amfi_code, fund_house, scheme_name, category, sub_category, plan, launch_date, benchmark, expense_ratio_pct, exit_load_pct, min_sip_amount, min_lumpsum_amount, fund_manager, risk_category, sebi_category_code]
Index: []

✅ Data quality report saved to reports/data_quality_report.csv